export const seedCars = [
  {
    id: "1",
    title: "Renault KWID (M)",
    brand: "Renault",
    type: "Hatchback",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 16000,
    seats: 5,
    mileageKm: 21000,
    yearOfManufacture: 2024,
    ownerName: "Ritesh",
    contactNumber: "8499857502",
    images: ["/src/assets/KWID IMAGE.jpeg"],
    featured: false,
    description: "Compact hatchback with modern design and excellent fuel efficiency. Perfect for city driving."
  },
  {
    id: "2",
    title: "Renault KIGER (M)",
    brand: "Renault",
    type: "SUV",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 79000,
    seats: 5,
    mileageKm: 55000,
    yearOfManufacture: 2022,
    ownerName: "Sahail",
    contactNumber: "8077995213",
    images: ["/src/assets/KIGER IMAGE.jpeg"],
    featured: false,
    description: "Compact SUV with modern design, good ground clearance, and comfortable cabin for urban adventures."
  },
  {
    id: "3",
    title: "Renault KIGER (M)",
    brand: "Renault",
    type: "SUV",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 79000,
    seats: 5,
    mileageKm: 70000,
    yearOfManufacture: 2023,
    ownerName: "Mahesh Kamireddy",
    contactNumber: "7901022036",
    images: ["/src/assets/KIGER IMAGE.jpeg"],
    featured: false,
    description: "Compact SUV with modern design, good ground clearance, and comfortable cabin for urban adventures."
  },
  {
    id: "4",
    title: "Honda CITY (M)",
    brand: "Honda",
    type: "Sedan",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 35000,
    seats: 5,
    mileageKm: 132000,
    yearOfManufacture: 2018,
    ownerName: "Satya Penumarthy",
    contactNumber: "8125500571",
    images: ["/src/assets/HONDA CITY IMAGE.jpeg"],
    featured: false,
    description: "Reliable sedan with Honda's engineering excellence, comfortable ride, and good fuel economy."
  },
  {
    id: "5",
    title: "Suzuki BALENO (M)",
    brand: "Suzuki",
    type: "Hatchback",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 79000,
    seats: 5,
    mileageKm: 18000,
    yearOfManufacture: 2024,
    ownerName: "Priyanka Metta",
    contactNumber: "9502087207",
    images: ["/src/assets/BALENO IMAGE.jpeg"],
    featured: true,
    description: "Popular hatchback known for reliability, low maintenance, and excellent fuel efficiency."
  },
  {
    id: "6",
    title: "Suzuki BREZZA VXI",
    brand: "Suzuki",
    type: "SUV",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 29000,
    seats: 5,
    mileageKm: 45000,
    yearOfManufacture: 2023,
    ownerName: "Hima Bindu",
    contactNumber: "—",
    images: ["/src/assets/BREZZA IMAGE.jpeg"],
    featured: false,
    description: "Compact SUV with modern design and good ground clearance for urban and highway driving."
  },
  {
    id: "7",
    title: "Suzuki DZIRE",
    brand: "Suzuki",
    type: "Sedan",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 16000,
    seats: 5,
    mileageKm: 61000,
    yearOfManufacture: 2011,
    ownerName: "Trinath Vasireddy",
    contactNumber: "9676696030",
    images: ["/src/assets/DZIRE IMAGE.jpeg"],
    featured: false,
    description: "Compact sedan with reliable performance and good fuel efficiency for daily commuting."
  },
  {
    id: "8",
    title: "Toyota GLANZA (M)",
    brand: "Toyota",
    type: "Hatchback",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 79000,
    seats: 5,
    mileageKm: 13000,
    yearOfManufacture: 2024,
    ownerName: "Santhosh Metta",
    contactNumber: "8099662446",
    images: ["/src/assets/GLANZA IMAGE.jpeg"],
    featured: true,
    description: "Premium hatchback with excellent fuel efficiency and Toyota reliability. Perfect for city driving and weekend getaways."
  },
  {
    id: "9",
    title: "Tata NEXON (AMT)",
    brand: "Tata",
    type: "SUV",
    transmission: "Automatic",
    fuel: "Petrol",
    pricePerDay: 30000,
    seats: 5,
    mileageKm: 22000,
    yearOfManufacture: 2024,
    ownerName: "Anand",
    contactNumber: "9603520402",
    images: ["/src/assets/NEXON IMAGE.jpeg"],
    featured: true,
    description: "India's safest electric vehicle with zero emissions, advanced features, and impressive range."
  },
  {
    id: "10",
    title: "Tata NEXON XZ+ (M)",
    brand: "Tata",
    type: "SUV",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 31000,
    seats: 5,
    mileageKm: 23000,
    yearOfManufacture: 2023,
    ownerName: "—",
    contactNumber: "—",
    images: ["/src/assets/NEXON IMAGE.jpeg"],
    featured: false,
    description: "Premium electric SUV with extended range and advanced features for eco-conscious drivers."
  },
  {
    id: "11",
    title: "Tata ALTROZ (AMT)",
    brand: "Tata",
    type: "Hatchback",
    transmission: "Automatic",
    fuel: "Petrol",
    pricePerDay: 79000,
    seats: 5,
    mileageKm: 25000,
    yearOfManufacture: 2023,
    ownerName: "Likitha Reddy",
    contactNumber: "9550193450",
    images: ["/src/assets/ALTROZ IMAGE.jpeg"],
    featured: false,
    description: "Premium hatchback with modern design, comfortable interior, and smooth automatic transmission."
  },
  {
    id: "12",
    title: "Hyundai i20 (M)",
    brand: "Hyundai",
    type: "Hatchback",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 79000,
    seats: 5,
    mileageKm: 55000,
    yearOfManufacture: 2018,
    ownerName: "Trinadh Konda",
    contactNumber: "8919254948",
    images: ["/src/assets/I20 IMAGE.jpeg"],
    featured: false,
    description: "Stylish hatchback with modern design, comfortable interior, and smooth performance for daily commuting."
  },
  {
    id: "13",
    title: "Kia SELTOS (M)",
    brand: "Kia",
    type: "SUV",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 35000,
    seats: 5,
    mileageKm: 21000,
    yearOfManufacture: 2024,
    ownerName: "Shashidhar",
    contactNumber: "9100400517",
    images: ["/src/assets/SELTOS IMAGE.jpeg"],
    featured: true,
    description: "Feature-rich SUV with modern design, premium interior, and excellent value for money."
  },
  {
    id: "14",
    title: "Kia SELTOS (M)",
    brand: "Kia",
    type: "SUV",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 35000,
    seats: 5,
    mileageKm: 8000,
    yearOfManufacture: 2024,
    ownerName: "Shashidhar",
    contactNumber: "9100400517",
    images: ["/src/assets/SELTOS IMAGE.jpeg"],
    featured: true,
    description: "Feature-rich SUV with modern design, premium interior, and excellent value for money."
  },
  {
    id: "15",
    title: "Kia CARENS",
    brand: "Kia",
    type: "MPV",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 40000,
    seats: 7,
    mileageKm: 60000,
    yearOfManufacture: 2023,
    ownerName: "A Shekar",
    contactNumber: "9652143129",
    images: ["/src/assets/CARENS IMAGE.jpeg"],
    featured: false,
    description: "Spacious 7-seater MPV with modern features and comfortable interior for family trips."
  },
  {
    id: "16",
    title: "Kia SONET",
    brand: "Kia",
    type: "SUV",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 28000,
    seats: 5,
    mileageKm: 20000,
    yearOfManufacture: 2024,
    ownerName: "Shashidhar",
    contactNumber: "9100400517",
    images: ["/src/assets/SONET IMAGE.jpeg"],
    featured: false,
    description: "Compact SUV with modern design and good features for urban driving."
  },
  {
    id: "17",
    title: "Mercedes-Benz C220d",
    brand: "Mercedes-Benz",
    type: "Sedan",
    transmission: "Automatic",
    fuel: "Petrol",
    pricePerDay: 69000,
    seats: 5,
    mileageKm: 67000,
    yearOfManufacture: 2018,
    ownerName: "EPIC STAR",
    contactNumber: "9154231684",
    images: ["/src/assets/MERCEDES C220D IMAGE.jpeg"],
    featured: true,
    description: "Luxury sedan with premium interior, advanced technology, and Mercedes-Benz refinement."
  },
  {
    id: "18",
    title: "Mercedes-Benz C220d",
    brand: "Mercedes-Benz",
    type: "Sedan",
    transmission: "Automatic",
    fuel: "Petrol",
    pricePerDay: 73000,
    seats: 5,
    mileageKm: 52000,
    yearOfManufacture: 2020,
    ownerName: "EPIC STAR",
    contactNumber: "9154231684",
    images: ["/src/assets/MERCEDES C220D IMAGE.jpeg"],
    featured: true,
    description: "Luxury sedan with premium interior, advanced technology, and Mercedes-Benz refinement."
  },
  {
    id: "19",
    title: "Mercedes-Benz C220d",
    brand: "Mercedes-Benz",
    type: "Sedan",
    transmission: "Automatic",
    fuel: "Petrol",
    pricePerDay: 79000,
    seats: 5,
    mileageKm: 24000,
    yearOfManufacture: 2022,
    ownerName: "EPIC STAR",
    contactNumber: "9154231684",
    images: ["/src/assets/MERCEDES C220D IMAGE.jpeg"],
    featured: true,
    description: "Luxury sedan with premium interior, advanced technology, and Mercedes-Benz refinement."
  },
  {
    id: "20",
    title: "Audi Q3 30 TDI",
    brand: "Audi",
    type: "SUV",
    transmission: "Automatic",
    fuel: "Petrol",
    pricePerDay: 73000,
    seats: 5,
    mileageKm: 73056,
    yearOfManufacture: 2018,
    ownerName: "EPIC STAR",
    contactNumber: "9154231684",
    images: ["/src/assets/AUDI Q3 IMAGE.jpeg"],
    featured: true,
    description: "Premium compact SUV with quattro all-wheel drive, sophisticated design, and cutting-edge technology."
  }
];
