export const seedCars = [
  {
    id: "1",
    title: "Toyota Glanza",
    brand: "Toyota",
    type: "Hatchback",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 1200,
    seats: 5,
    mileageKm: 25000,
    images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
    featured: true,
    description: "Premium hatchback with excellent fuel efficiency and Toyota reliability. Perfect for city driving and weekend getaways."
  },
  {
    id: "2",
    title: "BMW X1",
    brand: "BMW",
    type: "SUV",
    transmission: "Automatic",
    fuel: "Petrol",
    pricePerDay: 3500,
    seats: 5,
    mileageKm: 18000,
    images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
    featured: true,
    description: "Luxury compact SUV with premium features, sporty handling, and BMW's signature driving dynamics."
  },
  {
    id: "3",
    title: "Tata Nexon EV",
    brand: "Tata",
    type: "SUV",
    transmission: "Automatic",
    fuel: "EV",
    pricePerDay: 2000,
    seats: 5,
    mileageKm: 12000,
    images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
    featured: true,
    description: "India's safest electric vehicle with zero emissions, advanced features, and impressive range."
  },
  {
    id: "4",
    title: "Hyundai Verna",
    brand: "Hyundai",
    type: "Sedan",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 1800,
    seats: 5,
    mileageKm: 22000,
    images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
    featured: false,
    description: "Stylish sedan with modern design, comfortable interior, and smooth performance for daily commuting."
  },
  {
    id: "5",
    title: "Mahindra XUV700",
    brand: "Mahindra",
    type: "SUV",
    transmission: "Automatic",
    fuel: "Petrol",
    pricePerDay: 2800,
    seats: 7,
    mileageKm: 15000,
    images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3ZnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
    featured: true,
    description: "Premium 7-seater SUV with advanced safety features, powerful engine, and spacious cabin."
  },
  {
    id: "6",
    title: "Maruti Baleno",
    brand: "Maruti",
    type: "Hatchback",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 1000,
    seats: 5,
    mileageKm: 30000,
    images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
    featured: false,
    description: "Popular hatchback known for reliability, low maintenance, and excellent fuel efficiency."
  },
  {
    id: "7",
    title: "Kia Seltos",
    brand: "Kia",
    type: "SUV",
    transmission: "Automatic",
    fuel: "Petrol",
    pricePerDay: 2200,
    seats: 5,
    mileageKm: 20000,
    images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3ZnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
    featured: false,
    description: "Feature-rich SUV with modern design, premium interior, and excellent value for money."
  },
  {
    id: "8",
    title: "Honda City",
    brand: "Honda",
    type: "Sedan",
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 1600,
    seats: 5,
    mileageKm: 28000,
    images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3ZnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
    featured: false,
    description: "Reliable sedan with Honda's engineering excellence, comfortable ride, and good fuel economy."
  },
  // {
  //   id: "9",
  //   title: "MG ZS EV",
  //   brand: "MG",
  //   type: "SUV",
  //   transmission: "Automatic",
  //   fuel: "EV",
  //   pricePerDay: 2400,
  //   seats: 5,
  //   mileageKm: 8000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3ZnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: true,
  //   description: "Electric SUV with modern design, connected features, and impressive range for eco-conscious drivers."
  // },
  // {
  //   id: "10",
  //   title: "Skoda Slavia",
  //   brand: "Skoda",
  //   type: "Sedan",
  //   transmission: "Manual",
  //   fuel: "Petrol",
  //   pricePerDay: 2000,
  //   seats: 5,
  //   mileageKm: 16000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: false,
  //   description: "Premium sedan with European design, solid build quality, and engaging driving dynamics."
  // },
  // {
  //   id: "11",
  //   title: "Volkswagen Virtus",
  //   brand: "Volkswagen",
  //   type: "Sedan",
  //   transmission: "Automatic",
  //   fuel: "Petrol",
  //   pricePerDay: 1900,
  //   seats: 5,
  //   mileageKm: 14000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: false,
  //   description: "German engineering with premium feel, excellent safety ratings, and refined driving experience."
  // },
  // {
  //   id: "12",
  //   title: "Renault Kiger",
  //   brand: "Renault",
  //   type: "SUV",
  //   transmission: "Manual",
  //   fuel: "Petrol",
  //   pricePerDay: 1400,
  //   seats: 5,
  //   mileageKm: 25000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: false,
  //   description: "Compact SUV with modern design, good ground clearance, and comfortable cabin for urban adventures."
  // },
  // // Additional cars
  // {
  //   id: "13",
  //   title: "Mercedes-Benz A-Class",
  //   brand: "Mercedes-Benz",
  //   type: "Hatchback",
  //   transmission: "Automatic",
  //   fuel: "Petrol",
  //   pricePerDay: 4500,
  //   seats: 5,
  //   mileageKm: 12000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: true,
  //   description: "Luxury hatchback with premium interior, advanced technology, and Mercedes-Benz refinement."
  // },
  // {
  //   id: "14",
  //   title: "Audi Q3",
  //   brand: "Audi",
  //   type: "SUV",
  //   transmission: "Automatic",
  //   fuel: "Petrol",
  //   pricePerDay: 4200,
  //   seats: 5,
  //   mileageKm: 18000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: true,
  //   description: "Premium compact SUV with quattro all-wheel drive, sophisticated design, and cutting-edge technology."
  // },
  // {
  //   id: "15",
  //   title: "Tesla Model 3",
  //   brand: "Tesla",
  //   type: "Sedan",
  //   transmission: "Automatic",
  //   fuel: "EV",
  //   pricePerDay: 5000,
  //   seats: 5,
  //   mileageKm: 8000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: true,
  //   description: "Electric sedan with autopilot capabilities, minimalist design, and exceptional performance."
  // },
  // {
  //   id: "16",
  //   title: "Ford Mustang",
  //   brand: "Ford",
  //   type: "Sports",
  //   transmission: "Manual",
  //   fuel: "Petrol",
  //   pricePerDay: 3800,
  //   seats: 4,
  //   mileageKm: 15000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3ZnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: true,
  //   description: "Iconic American muscle car with powerful V8 engine, aggressive styling, and thrilling performance."
  // },
  // {
  //   id: "17",
  //   title: "Porsche 911",
  //   brand: "Porsche",
  //   type: "Sports",
  //   transmission: "Automatic",
  //   fuel: "Petrol",
  //   pricePerDay: 8000,
  //   seats: 4,
  //   mileageKm: 8000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3ZnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: true,
  //   description: "Legendary sports car with precision engineering, exceptional handling, and timeless design."
  // },
  // {
  //   id: "18",
  //   title: "Range Rover Sport",
  //   brand: "Land Rover",
  //   type: "SUV",
  //   transmission: "Automatic",
  //   fuel: "Petrol",
  //   pricePerDay: 6500,
  //   seats: 5,
  //   mileageKm: 12000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: true,
  //   description: "Luxury SUV with off-road capability, premium interior, and commanding presence on any terrain."
  // },
  // {
  //   id: "19",
  //   title: "Lexus ES",
  //   brand: "Lexus",
  //   type: "Sedan",
  //   transmission: "Automatic",
  //   fuel: "Hybrid",
  //   pricePerDay: 3200,
  //   seats: 5,
  //   mileageKm: 16000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: false,
  //   description: "Luxury sedan with hybrid powertrain, exceptional comfort, and legendary reliability."
  // },
  // {
  //   id: "20",
  //   title: "Volvo XC60",
  //   brand: "Volvo",
  //   type: "SUV",
  //   transmission: "Automatic",
  //   fuel: "Hybrid",
  //   pricePerDay: 3600,
  //   seats: 5,
  //   mileageKm: 14000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3ZnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: false,
  //   description: "Safety-focused SUV with Scandinavian design, hybrid efficiency, and advanced driver assistance."
  // },
  // {
  //   id: "21",
  //   title: "Jaguar F-Type",
  //   brand: "Jaguar",
  //   type: "Sports",
  //   transmission: "Automatic",
  //   fuel: "Petrol",
  //   pricePerDay: 5500,
  //   seats: 2,
  //   mileageKm: 10000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3ZnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: true,
  //   description: "British sports car with elegant design, powerful performance, and distinctive exhaust note."
  // },
  // {
  //   id: "22",
  //   title: "Bentley Continental GT",
  //   brand: "Bentley",
  //   type: "Luxury",
  //   transmission: "Automatic",
  //   fuel: "Petrol",
  //   pricePerDay: 12000,
  //   seats: 4,
  //   mileageKm: 5000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3ZnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: true,
  //   description: "Ultra-luxury grand tourer with handcrafted interior, exceptional performance, and unmatched refinement."
  // },
  // {
  //   id: "23",
  //   title: "Rolls-Royce Phantom",
  //   brand: "Rolls-Royce",
  //   type: "Luxury",
  //   transmission: "Automatic",
  //   fuel: "Petrol",
  //   pricePerDay: 20000,
  //   seats: 4,
  //   mileageKm: 3000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3ZnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: true,
  //   description: "The pinnacle of automotive luxury with bespoke craftsmanship, ultimate comfort, and unmatched prestige."
  // },
  // {
  //   id: "24",
  //   title: "Lamborghini Huracán",
  //   brand: "Lamborghini",
  //   type: "Supercar",
  //   transmission: "Automatic",
  //   fuel: "Petrol",
  //   pricePerDay: 15000,
  //   seats: 2,
  //   mileageKm: 2000,
  //   images: ["data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3ZnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+"],
  //   featured: true,
  //   description: "Exotic supercar with aggressive styling, incredible performance, and unmistakable Lamborghini character."
  // }
];
